blank_issues_enabled: true
contact_links:
  - name: Hazelcast Google Group
    url: https://groups.google.com/forum/#!forum/hazelcast
    about: We're not actively answering questions on GitHub so feel free to ask one on our Google Group
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/hazelcast
    about: We're not actively answering questions on GitHub so feel free to ask one on Stack Overflow
