package test.utils;

/**
 * @author Neil Stevenson
 */
public class Oscars {
  
    // https://en.wikipedia.org/wiki/Academy_Award_for_Best_Actor
    public static final Object[][] bestActors = {
            { 1928,     "Emil",         "Jannings"},
            { 1929,     "Warner",       "Baxter"},
            { 1930,     "George",       "Arliss"},
            { 1931,     "Lionel",       "Barrymore"},
            { 1932,     "Wallace",      "Beery"},
            { 1933,     "Charles",      "Laughton"},
            { 1934,     "Clark",        "Gable"},
            { 1935,     "Victor",       "McLaglen"},
            { 1936,     "Paul",         "Muni"},
            { 1937,     "Spencer",      "Tracy"},
            { 1938,     "Spencer",      "Tracy"},
            { 1939,     "Robert",       "Donat"},
            { 1940,     "James",        "Stewart"},
            { 1941,     "Gary",         "Cooper"},
            { 1942,     "James",        "Cagney"},
            { 1943,     "Paul",         "Lukas"},
            { 1944,     "Bing",         "Crosby"},
            { 1945,     "Ray",          "Milland"},
            { 1946,     "Fredric",      "March"},
            { 1947,     "Ronald",       "Colman"},
            { 1948,     "Laurence",     "Olivier"},
            { 1949,     "Broderick",    "Crawford"},
            { 1950,     "Jose",         "Ferrer"},
            { 1951,     "Humphrey",     "Bogart"},
            { 1952,     "Gary",         "Cooper"},
            { 1953,     "William",      "Holden"},
            { 1954,     "Marlon",       "Brando"},
            { 1955,     "Ernest",       "Borgnine"},
            { 1956,     "Yul",          "Brynner"},
            { 1957,     "Alec",         "Guinness"},
            { 1958,     "David",        "Niven"},
            { 1959,     "Charlton",     "Heston"},
            { 1960,     "Burt",         "Lancaster"},
            { 1961,     "Maximilian",   "Schell"},
            { 1962,     "Gregory",      "Peck"},
            { 1963,     "Sidney",       "Poitier"},
            { 1964,     "Rex",          "Harrison"},
            { 1965,     "Lee",          "Marvin"},
            { 1966,     "Paul",         "Scofield"},
            { 1967,     "Rod",          "Steiger"},
            { 1968,     "Cliff",        "Robertson"},
            { 1969,     "John",         "Wayne"},
            { 1970,     "George",       "Scott"},
            { 1971,     "Gene",         "Hackman"},
            { 1972,     "Marlon",       "Brando"},
            { 1973,     "Jack",         "Lemmon"},
            { 1974,     "Art",          "Carney"},
            { 1975,     "Jack",         "Nicholson"},
            { 1976,     "Peter",        "Finch"},
            { 1977,     "Richard",      "Dreyfuss"},
            { 1978,     "Jon",          "Voight"},
            { 1979,     "Dustin",       "Hoffman"},
            { 1980,     "Robert",       "De Niro"},
            { 1981,     "Henry",        "Fonda"},
            { 1982,     "Ben",          "Kingsley"},
            { 1983,     "Robert",       "Duvall"},
            { 1984,     "Murray",       "Abraham"},
            { 1985,     "William",      "Hurt"},
            { 1986,     "Paul",         "Newman"},
            { 1987,     "Michael",      "Douglas"},
            { 1988,     "Dustin",       "Hoffman"},
            { 1989,     "Daniel",       "Day-Lewis"},
            { 1990,     "Jeremy",       "Irons"},
            { 1991,     "Anthony",      "Hopkins"},
            { 1992,     "Al",           "Pacino"},
            { 1993,     "Tom",          "Hanks"},
            { 1994,     "Tom",          "Hanks"},
            { 1995,     "Nicolas",      "Cage"},
            { 1996,     "Geoffrey",     "Rush"},
            { 1997,     "Jack",         "Nicholson"},
            { 1998,     "Roberto",      "Benigni"},
            { 1999,     "Kevin",        "Spacey"},
            { 2000,     "Russell",      "Crowe"},
            { 2001,     "Denzel",       "Washington"},
            { 2002,     "Adrien",       "Brody"},
            { 2003,     "Sean",         "Penn"},
            { 2004,     "Jamie",        "Foxx"},
            { 2005,     "Philip",       "Seymour"},
            { 2006,     "Forest",       "Whitaker"},
            { 2007,     "Daniel",       "Day-Lewis"},
            { 2008,     "Sean",         "Penn"},
            { 2009,     "Jeff",         "Bridges"},
            { 2010,     "Colin",        "Firth"},
            { 2011,     "Jean",         "Dujardin"},
            { 2012,     "Daniel",       "Day-Lewis"},
            { 2013,     "Mathew",       "McConaughey"},
            { 2014,     "Eddie",        "Redmayne"},      
    };
    
}
