name: build
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
        hazelcast: [ '4.0.3', '4.1' ]
        architecture: [ 'x64' ]
    name: Build with JDK ${{ matrix.java }} and Hazelcast ${{ matrix.hazelcast }}
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}

      - uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -Dhazelcast.version=${{ matrix.hazelcast }} package

